apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fish-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/shlim0118/hama-deployment.git
    targetRevision: main
    path: fish
  destination:
    server: https://kubernetes.default.svc
    namespace: game
  syncPolicy:
    automated:
      prune: true
      selfHeal: true