apiVersion: apps/v1
kind: Deployment
metadata:
  name: example4-inflate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example4-inflate
  template:
    metadata:
      labels:
        app: example4-inflate
    spec:
      # 주석을 풀어서 실행해보세요
#      affinity:
#        nodeAffinity:
#          requiredDuringSchedulingIgnoredDuringExecution:
#           nodeSelectorTerms:
#           - matchExpressions:
#             - key: server
#               operator: In
#               values:
#                 - wild
      nodeSelector:
        server: "default"
      terminationGracePeriodSeconds: 0
      containers:
      - name: inflate
        image: public.ecr.aws/eks-distro/kubernetes/pause:3.7
        resources:
          requests:
            cpu: "1"
        securityContext:
          allowPrivilegeEscalation: false