apiVersion: apps/v1
kind: Deployment
metadata:
  name: inflate
  namespace: game
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inflate
  template:
    metadata:
      labels:
        app: inflate
    spec:
      # 주석을 풀어서 실행해보세요
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
           nodeSelectorTerms:
           - matchExpressions:
             - key: server
               operator: In
               values:
                 - farm
      nodeSelector:
        server: "farm"
      terminationGracePeriodSeconds: 0
      containers:
      - name: inflate
        image: public.ecr.aws/eks-distro/kubernetes/pause:3.7
        volumeMounts:
          - mountPath: /usr/share/nginx/html
            name: nginx-storage
        resources:
          requests:
            cpu: "1"
        securityContext:
          allowPrivilegeEscalation: false
      volumes:
        - name: nginx-storage
          persistentVolumeClaim:
            claimName: farm-pvc